scenarioList_orig = {
    {{'1a_100'},{1},{'TBMAC1a_increaseTrt'}};...
    {{'1b_100'},{1},{'TBMAC1b_increaseTrt'}};...
    {{'1_100'}, {1},{'TBMAC1a_increaseTrt'},{'TBMAC1b_increaseTrt'}};...
    {{'2_100'}, {1},{'TBMAC2a_initDefReduction'},{'TBMAC2b_trtSuccess'},{'TBMAC2c_MDRtrtSuccess'}};...
    {{'2a_100'},{1},{'TBMAC2a_initDefReduction'}};...
    {{'2b_100'},{1},{'TBMAC2b_trtSuccess'}};...
    {{'2c_100'},{1},{'TBMAC2c_MDRtrtSuccess'}};...
    {{'3_100'},{1},{'TBMAC3_XpertReplacesSmear'},{'TBMAC3b_XpertReplacesSmear_SSsensUp'}};...
    {{'4_100'}, {1},{'TBMAC4_activeCaseFinding'}};...
    {{'7_100'}, {1},{'TBMAC1a_increaseTrt'},{'TBMAC1b_increaseTrt'},...
    {'TBMAC2a_initDefReduction'},{'TBMAC2b_trtSuccess'},{'TBMAC2c_MDRtrtSuccess'},...
    {'TBMAC3_XpertReplacesSmear'},{'TBMAC3b_XpertReplacesSmear_SSsensUp'},...
    {'TBMAC4_activeCaseFinding'}};...
    };
scenarioList_adv ={
    {{'1a_adv'},{1},{'TBMAC1a_adv'}};...
    {{'1b_adv'},{1},{'TBMAC1b_adv'}};...
    {{'1_adv'}, {1},{'TBMAC1a_adv'},{'TBMAC1b_adv'}};...
    {{'2_adv'}, {1},{'TBMAC2a_adv'},{'TBMAC2b_adv'},{'TBMAC2c_adv'}};...
    {{'2a_adv'},{1},{'TBMAC2a_adv'}};...
    {{'2b_adv'},{1},{'TBMAC2b_adv'}};...
    {{'2c_adv'},{1},{'TBMAC2c_adv'}};...
    {{'3_adv'},{1},{'TBMAC3a_adv'},{'TBMAC3b_adv'}};...
    {{'4_adv'}, {1},{'Tbmac4_adv'}};...
    {{'5_adv'}, {1},{'TBMAC5_preventativeTherapyForLat'}};...
    {{'7_adv'}, {1},{'TBMAC1a_adv'},{'TBMAC1b_adv'},...
    {'TBMAC2a_adv'},{'TBMAC2b_adv'},{'TBMAC2c_adv'},...
    {'TBMAC3a_adv'},{'TBMAC3b_adv'}...
    {'Tbmac4_adv'},...
    {'TBMAC5_preventativeTherapyForLat'}};...
    };

% scenarioList_orig = {
%     {{'4_100'}, {1},{'TBMAC4_activeCaseFinding'}};...
%     {{'7_100'}, {1},{'TBMAC1a_increaseTrt'},{'TBMAC1b_increaseTrt'},...
%     {'TBMAC2a_initDefReduction'},{'TBMAC2b_trtSuccess'},{'TBMAC2c_MDRtrtSuccess'},...
%     {'TBMAC3_XpertReplacesSmear'},{'TBMAC3b_XpertReplacesSmear_SSsensUp'},...
%     {'TBMAC4_activeCaseFinding'}};...
%     };
% scenarioList_adv ={
%     {{'4_adv'}, {1},{'Tbmac4_adv'}};...
%     {{'7_adv'}, {1},{'TBMAC1a_adv'},{'TBMAC1b_adv'},...
%     {'TBMAC2a_adv'},{'TBMAC2b_adv'},{'TBMAC2c_adv'},...
%     {'TBMAC3a_adv'},{'TBMAC3b_adv'}...
%     {'Tbmac4_adv'},...
%     {'TBMAC5_preventativeTherapyForLat'}};...
%     };





% scenarioList_adv ={
%  {{'5_adv'}, {1},{'TBMAC5_preventativeTherapyForLat'}};...
%     };

%make the 0.75, 0.5, and 0.25
scenarioMultiplier = {};
scaleStrList = {'025','050','075'};
for j = 1:3
    scaleStr = scaleStrList{j};
    scenarioMultiplier{j} = scenarioList_orig;
    for rowNum = 1:size(scenarioList_orig,1)
        scenarioMultiplier{j}{rowNum}{1} = strrep(scenarioMultiplier{j}{rowNum}{1},'100',scaleStr);  %change the name
        scenarioMultiplier{j}{rowNum}{2} = {0.01*str2double(scaleStr)};  %change the multiplier value        
    end
end



%stack all the scenarios
scenarioList = [scenarioList_orig;scenarioMultiplier{1};scenarioMultiplier{2};scenarioMultiplier{3};scenarioList_adv];
% scenarioList = [scenarioList_orig;scenarioList_adv];  %DEBUGGING
% scenarioList = scenarioList_adv;  %DEBUGGING

overWriterFoldNameList = {{'base'}};
for row = 1:size(scenarioList,1)
    overWriterFoldNameList{1,row+1} = scenarioList{row}{1};
end

foldNameList = [overWriterFoldNameList{:}];
